### ISSUE TITLE
Cypher bug

### ISSUE THREAD

**Issue by FunixG** [Hospyboard/api#19]
Caused by: java.lang.IllegalStateException: Cipher not initialized
        at java.base/javax.crypto.Cipher.checkCipherState(Cipher.java:1790) ~[na:na]
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2197) ~[na:na]
        at com.hospyboard.api.app.core.db_converters.AEncryptionDatabase.convertToEntity(AEncryptionDatabase.java:51) ~[classes!/:1.0]
        at com.hospyboard.api.app.core.db_converters.EncryptionDatabaseString.convertToEntityAttribute(EncryptionDatabaseString.java:24) ~[classes!/:1.0]
        at com.hospyboard.api.app.core.db_converters.EncryptionDatabaseString.convertToEntityAttribute(EncryptionDatabaseString.java:10) ~[classes!/:1.0]
        at org.hibernate.metamodel.model.convert.internal.JpaAttributeConverterImpl.toDomainValue(JpaAttributeConverterImpl.java:45) ~[hibernate-core-5.6.7.Final.jar!/:5.6.7.Final]
        at org.hibernate.type.descriptor.converter.AttributeConverterSqlTypeDescriptorAdapter$2.doConversion(AttributeConverterSqlTypeDescriptorAdapter.java:140) ~[hibernate-core-5.6.7.Final.jar!/:5.6.7.Final]
        ... 130 common frames omitted

**Comment by FunixG** [comment]
old because it was old server
